### ISSUE TITLE
How to re-enable audio

### ISSUE THREAD

**Issue by timelf123** [fpm5022/Ping-Pong#33]
Thanks for the work you guys put in!

I picked up your fork as a base and am trying to get audio working. I tried uncommenting all the audio logic and generated an audiosprite, but no audio and no errors. Is that the same experience you had?

**Comment by mr-feek** [comment]
Hi Tim,

I do recall having audio errors, and ended up commenting out all of the audio code because we had no intention of using audio anyway. 

I'd recommend looking at the initial base project and building the audio for that and see if it works. In that case you could diff a few files and see if we accidentally deleted some important lines. 

Good luck with the project! We more or less hacked around (we had 0 experience with node, react, or a photon unit) so apologies for sloppy code in places!

**Comment by timelf123** [comment]
Thanks @fpm5022 we are starting with no React/photon experience either. It's a fun project!

Are you planning on maintaining / updating this repo or is your implementation done?

**Comment by mr-feek** [comment]
We are done with this implementation for the foreseeable future. A few friends and I built this at a company we were interning at, and are now back at school. 

I definitely may pick it back up again in the summer, but it would be best for you to contribute to your own fork.

**Comment by timelf123** [comment]
Thanks!
